### ISSUE TITLE
vendor report not working

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#94]
I am trying to pull the vendor subscription report from beacon and am getting a network error.  I tried on multiple PC's

**Comment by bsmithgall** [comment]
This is a unicode-related bug:

``` pytb
File "/app/purchasing/opportunities/admin/views.py", line 241, in stream 
    yield '\t'.join([str(i) for i in row]) + '\n'
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 5: ordinal not in range(128) 
```

I'll try to get to it tomorrow or this weekend.

**Comment by bsmithgall** [comment]
Still bugged for some reason.

**Comment by bsmithgall** [comment]
Actually, it looks like this is a problem that is coming about because of a limitation with Heroku long-polling responses. This is going to be a little heavier of a fix I think.

**Comment by bsmithgall** [comment]
@rileystewart this has been fixed for now.

**Comment by rileystewart** [comment]
I am still not able to pull this report like I used to be able to.  All the columns are not coming through correctly in excel and it is being mixed with wording from actual solicitations

(i tried to attach but it won't let me because it won't change from a tsv file type)
